#liulinsheng@wind-mobi.com 20171023 begin
# In case the platform does NOT support this type of sensors
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y   += usb_temp_check.o 

#liulinsheng@wind-mobi.com 20171023 end