#liulinsheng@wind-mobi.com 20171023 begin
# In case the platform does NOT support this type of sensors
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-$(CONFIG_WIND_ASUS_USB_TEMP_CHECK) += usb_temp_check.o 

#liulinsheng@wind-mobi.com 20171023 end
